# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-25 07:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('assignment_type', models.CharField(blank=True, choices=[('Essay', 'Essay'), ('Others', 'Others')], max_length=50, null=True)),
                ('discipline', models.CharField(blank=True, max_length=50, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_on', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('estimated_budget', models.IntegerField()),
                ('status', models.CharField(choices=[('Initiated', 'Initiated'), ('In Progress', 'In Progress'), ('In Review', 'In Review'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], max_length=50)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha_app.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
