# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-26 07:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_app', '0003_auto_20170325_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='made_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
