# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-26 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_app', '0004_auto_20170326_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'Initiated'), (1, 'In Progress'), (2, 'In Review'), (3, 'Completed'), (4, 'Canceled')], max_length=50),
        ),
    ]
