# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_app', '0007_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EURO', 'EURO'), ('POUND', 'POUND')], default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
